services:
  tracky:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"

  mongo:
    ports:
      - "27017:27017"

  eventstore:
    ports:
      - "2113:2113"
      - "1113:1113"
